collegeproject/collegeapp/urls.py
from django.urls import path
from . import views

from .views import get_courses
from .views import my_view

urlpatterns = [
  path('',views.index,name='index'),
  path('register/', views.register, name='register'),
  path('login/', views.login, name='login'),
  path('logout', views.logout, name='logout'),
  path('form/',views.form,name='form'),
  path('get_courses/', get_courses, name='get_courses'),
  path('my_view/', my_view, name='my_view'),

]

collegeproject/collegeproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from collegeproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('collegeapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

collegeproject/collegeapp/models.py
from django.db import models

class Department(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(max_length=100)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

collegeproject/collegeapp/forms.py
from django import forms
from .models import Department,Course



class MyForm(forms.Form):
    departments = Department.objects.all()
    department_choices = [(department.id, department.name) for department in departments]

    courses = Course.objects.all()
    course_choices = [(course.id, course.name) for course in courses]

    department = forms.ChoiceField(choices=[('', 'Select Department')] + department_choices)
    course = forms.ChoiceField(choices=[('', 'Select Course')] + course_choices)

collegeproject/collegeapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.http import JsonResponse
from .models import Course
from django.shortcuts import render
from .forms import MyForm


def my_view(request):
    message = None
    if request.method == 'POST':
        form = MyForm(request.POST)
        if form.is_valid():
            message = "Order Confirmed"
    else:
        form = MyForm()
    return render(request, 'template.html', {'form': form , 'message': message})


def get_courses(request):
    department_id = request.GET.get('department_id')
    courses = Course.objects.filter(department_id=department_id).values('id', 'name')
    return JsonResponse(list(courses), safe=False)


def index(request):
    return render(request,"index.html")



def register(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        cpassword = request.POST.get('password1', '')

        if username and password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username already taken')
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                messages.success(request, 'User created successfully')
                return redirect('login')
        else:
            messages.error(request, 'Invalid username or passwords do not match')

    return render(request, 'register.html')


# def register(request):
#     if request.method == 'POST' :
#         username = request.POST['username','']
#         password = request.POST['password','']
#         cpassword = request.POST['password1','']
#         if password == cpassword:
#             if User.objects.filter(username=username).exists():
#                 messages.info(request,'username taken')
#                 return redirect('register')
#             else:
#                 user=User.objects.create_user(username=username,password=password)
#                 user.save();
#                 messages.info(request, 'user created')
#         else :
#             messages.info(request, 'password not matching')
#             return redirect('register')
#         return render(request,'login.html')
#     return render(request,'register.html')
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return render(request,'empty.html')
        else:
            messages.info(request, 'invalid credentials')
            return redirect('login')
    return render(request,"login.html")
def logout(request):
    auth.logout(request)
    return redirect('/')

def form(request):
    return render(request,'form.html')

collegeproject/templates/empty.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>Title</title>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Online School Store</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active"  href="#">Home</a>
            </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'register' %}">Registration</a>
              </li>
              <li class="nav-item">
               <a class="nav-link active" href="{% url 'login' %}">Login</a>
              </li>
		       {% if user.is_authenticated %}
		         <li class="nav-item">
                  <a class="nav-link active" >hello {{user.username}}</a>
                 </li>

		         <li class="nav-item">
				  <a class="nav-link active" href="{% url 'logout' %}">logout</a>
                 </li>
               {% endif %}
                <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle nav-link active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Department</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science" target="_blank">Computer Science</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce" target="_blank">Commerce</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mathematics" target="_blank">Mathematics</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Science" target="_blank">Science</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities" target="_blank">Humanities</a>
                    <!-- Add more departments as needed -->
                  </div>
                </li>
          </ul>
        </div>
  </div>
</nav>

<div>
    <div class="container">
        <div class="row">
            <div class="cd-sm-12">
                <br>
                <br>
                <h4>For purchasing school items click below</h4>
              <a href="{% url 'my_view' %}" class="btn btn-outline-secondary">Just Click</a>
            </div>
        </div>
    </div>
</div>
</body>
</html>

collegeproject/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>


<!--{% csrf_token %}-->
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Online School Store</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active"  href="#">Home</a>
            </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'register' %}">Registration</a>
              </li>
              <li class="nav-item">
               <a class="nav-link active" href="{% url 'login' %}">Login</a>
              </li>
		       {% if user.is_authenticated %}
		         <li class="nav-item">
                  <a class="nav-link active" >hello {{user.username}}</a>
                 </li>

		         <li class="nav-item">
				  <a class="nav-link active" href="{% url 'logout' %}">logout</a>
                 </li>
               {% endif %}
                <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle nav-link active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Department</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science" target="_blank">Computer Science</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce" target="_blank">Commerce</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mathematics" target="_blank">Mathematics</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Science" target="_blank">Science</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities" target="_blank">Humanities</a>
                    <!-- Add more departments as needed -->
                  </div>
                </li>
          </ul>
        </div>
  </div>
</nav>



<div>
    <div class="container">
        <div class="row">
            <div class="cd-sm-12">
                <br>
                <br>
                <h3><i><strong>Better Education For Better World</strong></i></h3>
              <a href="{% url 'login' %}" class="btn btn-outline-secondary">Login</a>
            </div>
        </div>
    </div>
</div>

</body>
</html>

collegeproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Online School Store</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active"  href="#">Home</a>
            </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'register' %}">Registration</a>
              </li>
              <li class="nav-item">
               <a class="nav-link active" href="{% url 'login' %}">Login</a>
              </li>
		       {% if user.is_authenticated %}
		         <li class="nav-item">
                  <a class="nav-link active" >hello {{user.username}}</a>
                 </li>

		         <li class="nav-item">
				  <a class="nav-link active" href="{% url 'logout' %}">logout</a>
                 </li>
               {% endif %}
                <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle nav-link active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Department</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science" target="_blank">Computer Science</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce" target="_blank">Commerce</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mathematics" target="_blank">Mathematics</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Science" target="_blank">Science</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities" target="_blank">Humanities</a>
                    <!-- Add more departments as needed -->
                  </div>
                </li>
          </ul>
        </div>
  </div>
</nav>
<div class="container-fluid">
<h1>Login Page</h1>
<form action=" " method="post" >
  {% csrf_token %}
  <input type="text" name="username" placeholder="enter your username" ><br>
  <input type="password" name="password" placeholder="enter your password" ><br>
  <input type="submit">
</form>
<h4>Need an account?</h4><a href="{% url 'register' %}">Registration</a>

{% for msgss in messages %}
{{msgss}}
{% endfor %}
</div>
</body>
</html>

collegeproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Online School Store</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active"  href="#">Home</a>
            </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'register' %}">Registration</a>
              </li>
              <li class="nav-item">
               <a class="nav-link active" href="{% url 'login' %}">Login</a>
              </li>
		       {% if user.is_authenticated %}
		         <li class="nav-item">
                  <a class="nav-link active" >hello {{user.username}}</a>
                 </li>

		         <li class="nav-item">
				  <a class="nav-link active" href="{% url 'logout' %}">logout</a>
                 </li>
               {% endif %}
                <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle nav-link active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Department</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science" target="_blank">Computer Science</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce" target="_blank">Commerce</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mathematics" target="_blank">Mathematics</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Science" target="_blank">Science</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities" target="_blank">Humanities</a>
                    <!-- Add more departments as needed -->
                  </div>
                </li>
          </ul>
        </div>
  </div>
</nav>

<div class="container-fluid">
<h1>Registration</h1>
<form action="" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username"><br>
    <input type="password" name="password" placeholder="Password"><br>
    <input type="password" name="password1" placeholder="Confirm Password"><br>
    <input type="submit">
</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
</div>
</body>
</html>

collegeproject/templates/template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Online School Store</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active"  href="#">Home</a>
            </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'register' %}">Registration</a>
              </li>
              <li class="nav-item">
               <a class="nav-link active" href="{% url 'login' %}">Login</a>
              </li>
		       {% if user.is_authenticated %}
		         <li class="nav-item">
                  <a class="nav-link active" >hello {{user.username}}</a>
                 </li>

		         <li class="nav-item">
				  <a class="nav-link active" href="{% url 'logout' %}">logout</a>
                 </li>
               {% endif %}
                <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle nav-link active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Department</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science" target="_blank">Computer Science</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce" target="_blank">Commerce</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mathematics" target="_blank">Mathematics</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Science" target="_blank">Science</a>
                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities" target="_blank">Humanities</a>
                    <!-- Add more departments as needed -->
                  </div>
                </li>
          </ul>
        </div>
  </div>
</nav>

<br>
<div class="container-fluid">
<form method="post" id="myForm">

    <label for="Name">Name:</label>
    <input type="text" name="username" placeholder="Enter your name" id="Name" required><br>
    <label for="date">Date of birth:</label>
    <input type="date" name="dateofbirth" id="date" required><br>
    <label for="age">Age:</label>
    <input type="number" name="age" placeholder="Enter your age" id="age" required><br>
    <label for="address">Permanent Address: </label>
    <input type="text" name="address" placeholder="Enter your address" id="address" required><br>
    <label for="email">Email ID:</label>
    <input type="email" name="email" placeholder="Enter your email" id="email" required><br>
    <label for="id_phone_number">Phone Number:</label>
    <input type="text" name="phone_number" id="id_phone_number" maxlength="10" pattern="[0-9]*" title="Please enter only numeric characters (0-9)" placeholder="Enter 10-digit phone number">
    {% csrf_token %}
    {{ form.as_p }}
    <label for="purpose">Purpose:</label>
      <select id="purpose" name="purpose" required>
          <option value="">-------</option>
        <option value="enquiry">For Enquiry</option>
        <option value="order">Place Order</option>
        <option value="return">Return</option>
      </select><br>
    <label for="gender-male">Male</label>
    <input type="radio" id="gender-male" name="gender" value="male" required>
    <label for="gender-female">Female</label>
    <input type="radio" id="gender-female" name="gender" value="female" required><br>

    <h5>Materials Required :</h5>
    <label for="material-notebook">Notebook</label>
    <input type="checkbox" id="material-notebook" name="materials" value="notebook">
    <label for="material-pen">Pen</label>
    <input type="checkbox" id="material-pen" name="materials" value="pen">
    <label for="material-exam-papers">Exam Papers</label>
    <input type="checkbox" id="material-exam-papers" name="materials" value="exam_papers"><br>
    <label for="debit-notebook">Debit Notebook</label>
    <input type="checkbox" id="debit-notebook" name="materials" value="notebook">
    <label for="textbook">Text books</label>
    <input type="checkbox" id="textbook" name="materials" value="notebook"><br>
    <input type="submit" value="Submit">
</form>

{% if message %}
    <p>{{ message }}</p>
    <p><a href="{% url 'index' %}">Return to Home Page</a></p>
{% endif %}

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function(){
        $('#id_department').change(function(){
            var department_id = $(this).val();
            $.ajax({
                url: '/get_courses/',
                data: {'department_id': department_id},
                success: function(data){
                    var options = '<option value="">---------</option>';
                    for (var i = 0; i < data.length; i++) {
                        options += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
                    }
                    $('#id_course').html(options);
                }
            });
        });
    });
</script>

</div>
</body>
</html>